name: Continuous Deployment

on:
  pull_request:
    types: [closed]
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Say Hi
        run: echo "Hi"