name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Python Flask App CI Pipeline"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Say Hi
        run: echo "Hi"