name: Go App CI Pipeline
on:
  push:
    paths:
      - "go-app/**"
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "go-app/**"
    branches: [main]

jobs:
  go-app-ci:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Go Environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version: "1.23"

      - name: Format Code
        run: |
          cd go-app/
          gofmt -w .

      - name: Commit and Push Formatting Changes
        if: success()
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m 'chore(Go-Excel): Automated Code Formatting' && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Create .env file
        run: |
          touch go-app/.env

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
            context: go-app
            file: go-app/Dockerfile
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            load: true
