name: Go App CI Pipeline

on:
  push:
    paths:
      - "go-app/**"
    branches:
      - main
  pull_request:
    paths:
      - "go-app/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Go Environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version: "1.23"
          cache: true

      - name: Format Go Code
        run: |
          cd go-app
          gofmt -w .
        continue-on-error: false

      - name: Commit and Push Changes to PR Branch
        if: success()
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m '[CHORE] Automated Code Formatting' && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Go App
        run: |
          cd go-app
          go build ./...
