name: CI NestJS API
on:
  push:
    paths:
      - "nest-app/**"
    branches: [main]
  pull_request:
    paths:
      - "nest-app/**"
    branches: [main]

jobs:
  CI-NestJS-API:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.18.2"

      - name: Cache NestJS API dependencies
        uses: actions/cache@v4.2.0
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-nest-api-${{ hashFiles('nest-app/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nest-api-

      - name: Install Dependencies
        run: |
          npm install -g pnpm
          cd nest-app
          pnpm install

      - name: Format Code
        run: |
          cd nest-app
          pnpm run format

      - name: Build Application
        run: |
          cd nest-app
          pnpm run build

      - name: Commit and Push Formatting Changes
        if: success()
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -u
          git diff --quiet && git diff --staged --quiet || (git commit -m 'chore(nest-api): Automated Code Formatting' && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
