name: Python Flask App CI Pipeline

on:
  push:
    paths:
      - 'python-app/**'
    branches:
      - main
  pull_request:
    paths:
      - 'python-app/**'
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Setup Python Environment
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'

      - name: Ensure requirements.txt exists
        run: |
          if [ ! -f python-app/requirements.txt ]; then
            echo "File requirements.txt not found"
            exit 1
          fi
  
      - name: Install Dependencies
        run: |
            cd python-app/
            python -m pip install --upgrade pip
            pip install -r requirements.txt
