name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                app: [go-app, nest-app, python-app, react-app]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4.2.2

            # Go App
            - name: Setup Go Environment
              if: matrix.app == 'go-app'
              uses: actions/setup-go@v5.3.0
              with:
                go-version: '1.23'

            - name: Build Go App
              if: matrix.app == 'go-app'
              run: |
                cd go-app
                go build ./...

            # Nest App
            - name: Setup Node.js Environment for NestJS
              if: matrix.app == 'nest-app'
              uses: actions/setup-node@v4.1.0
              with:
                node-version: '22'

            - name: Install pnpm
              if: matrix.app == 'nest-app'
              run: |
                npm install -g pnpm

            - name: Build NestJS App
              if: matrix.app == 'nest-app'
              run: |
                cd nest-app
                pnpm install
                pnpm run build

            # Python App
            - name: Setup Python Environment
              if: matrix.app == 'python-app'
              uses: actions/setup-python@v5.3.0
              with:
                python-version: '3.10'

            - name: Build Flask App
              if: matrix.app == 'python-app'
              run: |
                cd python-app
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt

            # React App
            - name: Setup Node.js Environment for React
              if: matrix.app == 'react-app'
              uses: actions/setup-node@v4.1.0
              with:
                node-version: '22'

            - name: Install pnpm
              if: matrix.app == 'react-app'
              run: |
                npm install -g pnpm

            - name: Build React App
              if: matrix.app == 'react-app'
              run: |
                cd react-app
                pnpm install
                pnpm run build
